try:
    a = 256/8

except Exception as e:
    print(e)

# else gets executed when there is no error in the try block

else:
    print("I am a data scientist")